### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by sgonauer6wind**
Hi,

This pull-request bring a few fixes for issues found during build and testing against IXIA

### CODE REVIEW

**Review by micron10 — COMMENTED** [review]
After apply this patch CHAP_MD5 stop work .


log: 

[2022-03-08 17:56:48.126] eth1: recv [PPPoE PADI 9a:ee:e3:61:f5:18 => ff:ff:ff:ff:ff:ff sid=0000 <Service-Name test> <Host-Uniq c7000000000000007b010000>]
[2022-03-08 17:56:48.126] eth1: send [PPPoE PADO 6e:3a:11:37:75:e1 => 9a:ee:e3:61:f5:18 sid=0000 <AC-Name TEST> <Service-Name test> <AC-Cookie 50ab44c205b5dcfbf821701b372d99f73c000664964c1b30> <Host-Uniq c7000000000000007b010000>]
[2022-03-08 17:56:48.126] eth1: recv [PPPoE PADR 9a:ee:e3:61:f5:18 => 6e:3a:11:37:75:e1 sid=0000 <Service-Name test> <Host-Uniq c7000000000000007c010000> <AC-Cookie 50ab44c205b5dcfbf821701b372d99f73c000664964c1b30>]
[2022-03-08 17:56:48.126] eth1: send [PPPoE PADS 6e:3a:11:37:75:e1 => 9a:ee:e3:61:f5:18 sid=0001 <AC-Name TEST> <Service-Name test> <Host-Uniq c7000000000000007c010000>]
[2022-03-08 17:56:48.126] eth1: : lcp_layer_init
[2022-03-08 17:56:48.126] eth1: : auth_layer_init
[2022-03-08 17:56:48.126] eth1: : ccp_layer_init
[2022-03-08 17:56:48.126] eth1: : ipcp_layer_init
[2022-03-08 17:56:48.126] eth1: : ipv6cp_layer_init
[2022-03-08 17:56:48.126] eth1: : ppp establishing
[2022-03-08 17:56:48.126] eth1: 9f919c1c97f51e7b: lcp_layer_start
[2022-03-08 17:56:48.180] eth1: 9f919c1c97f51e7b: lcp_layer_started
[2022-03-08 17:56:48.180] eth1: 9f919c1c97f51e7b: auth_layer_start
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: terminate
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: lcp_layer_finish
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: auth_layer_finish
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: auth_layer_finished
[2022-03-08 17:57:08.308] eth1: recv [PPPoE PADT 9a:ee:e3:61:f5:18 => 6e:3a:11:37:75:e1 sid=0001]
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: pppoe: ppp finished
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: lcp_layer_free
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: auth_layer_free
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: ccp_layer_free
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: ipcp_layer_free
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: ipv6cp_layer_free
[2022-03-08 17:57:08.308] eth1: send [PPPoE PADT 6e:3a:11:37:75:e1 => 9a:ee:e3:61:f5:18 sid=0001 <AC-Name TEST> <Service-Name test>]
[2022-03-08 17:57:08.308] eth1: 9f919c1c97f51e7b: disconnected

**Comment by sgonauer6wind** [comment]
Hi,

I analyzed and pushed a fixed version. Sorry for the inconvenience

**Comment by micron10** [comment]
Yes now work fine .

Thanks for fast fix.

m.

**Review by nuclearcat — APPROVED** [review]

**Comment by sgonauer6wind** [comment]
Any news ?

**Pull request merged**
