### PR TITLE
Create INSTALL.debian.md

### PR DESCRIPTION
**Pull request by alex-eri**

### CODE REVIEW

**Comment by DmitriyEshenko** [comment]
Hi @alex-eri, maybe better to use readthedocs in this case?
https://github.com/accel-ppp/accel-ppp-docs/blob/master/installation/debian.rst
https://accel-ppp.readthedocs.io/en/latest/installation/debian.html

**Comment by alex-eri** [comment]
There is no link to docs. I never seen readthedocs pages for acell-ppp before and i used only xebds site for documentation.

I going to another my host to copy-paste instructions from bash history several times... Last two I looked at my PR =)

You free to close this PR. But pls add docs bage on top of README. Thanks.

**Comment by alex-eri** [comment]
I can full debianize code for making with dpkg. Is it needed?

**Comment by streamthing** [comment]
@alex-eri yes, please add accel-ppp to apt

**Pull request closed without merging**
