### PR TITLE
Add interim update script for pppd_compat

### PR DESCRIPTION
**Pull request by boomer41**
When the delegated IPv6 prefix is not set by radius beforehand, the ip-up script will not be able to handle the prefix, as the DHCPv6 stuff is happening way after the ip-up script.
To allow some sort of script to handle the dynamic delegation of a prefix, add an interim-update script.
An example scenario would be the addition of some firewall rules for the prefix.

This script is called exactly the same as the ip-up script.

### CODE REVIEW

**Comment by DmitriyEshenko** [comment]
Hi @boomer41, potentially it can be taken negative effect, I mean run script on each interim update packets. Maybe it is possible to do what you want without running script on each interim-update

**Comment by boomer41** [comment]
Hi @DmitriyEshenko,

I tried, but no other script is being called when the DHCPv6 server assigns a delegated prefix.
The up script is triggered when the IPv6 address is assigned. As the prefix delegation is run asynchronously *after* IPv6 has been set up, it won't trigger. 

The only way I can see without this is to have some magic in the RADIUS server, which then in turn must send another RPC call back to the BRAS to execute a script. And only if the PD has triggered.
This feels ridiculous.

**Comment by svlobanov** [comment]
I believe we shouldn't touch radius part to implement dhcpv6 scripting. It should be done in dhcvp6 code

**Comment by boomer41** [comment]
> I believe we shouldn't touch radius part to implement dhcpv6 scripting. It should be done in dhcvp6 code

Would there be an alternative way of implementing it, then?
We need some way of adding some firewall rules and running some custom script when a prefix is delegated.

**Comment by DmitriyEshenko** [comment]
I think in this case more suitable will be implement Accounting Start Delay, like this do Cisco and Juniper vendors
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/security/a1/sec-a1-cr-book/sec-cr-a1.html#wp2228885570
https://www.juniper.net/documentation/en_US/junose15.1/information-products/topic-collections/command-reference-a-m/index.html?topic-80600.html
We know that pppd compat up scripts run after get response on Acct type start packet

**Pull request closed without merging**
