### PR TITLE
pppd_compat: add Framed-Interface-Id attribute support in radattr

### PR DESCRIPTION
**Pull request by ZBoris7**
This PR adds support for the Framed-Interface-Id attribute for radattr in the pppd_compat module.

### CODE REVIEW

**Review by DmitriyEshenko — APPROVED** [review]

**Review by svlobanov — COMMENTED** [review]
@ZBoris7 could you please provide a reference to specification (e.g. RFC document) that describes this endianness transformation?

**Comment by nuclearcat** [comment]
As i see attribute documented in: https://datatracker.ietf.org/doc/html/rfc3162#section-3.2
and Interface-Identifier in https://datatracker.ietf.org/doc/html/rfc2472#section-4.1.
```
Assuming that interface identifier bits are numbered from 0 to 63
     in canonical bit order where the most significant bit is the bit
     number 0
```
```
IEEE documentation lists the Ethernet addresses with the most significant byte on the left.  Inside each byte, the leftmost bit is the most significant bit and the rightmost bit is the least significant bit.  This is referred to as the canonical bit order.
```

**Comment by nuclearcat** [comment]
This is how it is printed in ppp-project:
https://github.com/ppp-project/ppp/blob/9b222dbe0e0231ff659c0171594ecead664652a7/pppd/ipv6cp.c#L409
https://github.com/ppp-project/ppp/blob/9b222dbe0e0231ff659c0171594ecead664652a7/pppd/ipv6cp.c#L424
https://github.com/ppp-project/ppp/blob/9b222dbe0e0231ff659c0171594ecead664652a7/pppd/eui64.c#L48
eui64_t definition https://github.com/ppp-project/ppp/blob/9b222dbe0e0231ff659c0171594ecead664652a7/pppd/eui64.h#L51

**Comment by svlobanov** [comment]
I've checked this implementation, it works fine at least on aarch64 linux:

freeradius config:
```
# cat /etc/freeradius/3.0/users | grep Framed-Interface-Id -B 1
username Cleartext-Password := "pass"
     Framed-Interface-Id := 0102:0304:0506:0708
```

freeradius log:
```
(0) Sent Access-Accept Id 1 from 127.0.0.1:1812 to 127.0.0.1:52372 length 30
(0)   Framed-Interface-Id = 102:304:506:708
```

accel-pppd radattr:
```
# cat /var/run/radattr.ppp0 
Framed-Interface-Id 102:304:506:708
```

@ZBoris7 please change commit message to normal one, e.g. "pppd_compat: add Framed-Interface-Id attribute support in radattr". Current commit message is not informative

**Review by svlobanov — APPROVED** [review]
LGTM

**Pull request merged**
